<?php

namespace ContainerGixtYKL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomepageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aZ0gdaJ.App\Entity\Homepage' shared service.
     *
     * @return \App\Entity\Homepage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aZ0gdaJ": it references class "App\\Entity\\Homepage" but no such service exists.');
    }
}
