<?php

namespace ContainerIzHNJVR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AZ0gdaJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aZ0gdaJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aZ0gdaJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'homepage' => ['privates', '.errored..service_locator.aZ0gdaJ.App\\Entity\\Homepage', NULL, 'Cannot autowire service ".service_locator.aZ0gdaJ": it references class "App\\Entity\\Homepage" but no such service exists.'],
        ], [
            'homepage' => 'App\\Entity\\Homepage',
        ]);
    }
}
